//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.21 at 07:38:56 PM COT 
//


package com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="wallet_id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="id_method_payment" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="mount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="tokenFirebase" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "token",
    "walletId",
    "idMethodPayment",
    "mount",
    "type",
    "tokenFirebase"
})
@XmlRootElement(name = "addBalanceRequest")
public class AddBalanceRequest {

    @XmlElement(required = true)
    protected String token;
    @XmlElement(name = "wallet_id", required = true)
    protected BigInteger walletId;
    @XmlElement(name = "id_method_payment", required = true)
    protected BigInteger idMethodPayment;
    @XmlElement(required = true)
    protected BigInteger mount;
    @XmlElement(required = true)
    protected BigInteger type;
    @XmlElement(required = true)
    protected String tokenFirebase;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the walletId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWalletId() {
        return walletId;
    }

    /**
     * Sets the value of the walletId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWalletId(BigInteger value) {
        this.walletId = value;
    }

    /**
     * Gets the value of the idMethodPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdMethodPayment() {
        return idMethodPayment;
    }

    /**
     * Sets the value of the idMethodPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdMethodPayment(BigInteger value) {
        this.idMethodPayment = value;
    }

    /**
     * Gets the value of the mount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMount() {
        return mount;
    }

    /**
     * Sets the value of the mount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMount(BigInteger value) {
        this.mount = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setType(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the tokenFirebase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenFirebase() {
        return tokenFirebase;
    }

    /**
     * Sets the value of the tokenFirebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenFirebase(String value) {
        this.tokenFirebase = value;
    }

}
