//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.19 at 05:42:11 PM COT 
//


package com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LicensePlateBus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SeatedPassengerCapacity" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="StandingPassengerCapacity" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="debtCollectorIdUser" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bus", propOrder = {
    "licensePlateBus",
    "model",
    "seatedPassengerCapacity",
    "standingPassengerCapacity",
    "debtCollectorIdUser"
})
public class Bus {

    @XmlElement(name = "LicensePlateBus", required = true)
    protected String licensePlateBus;
    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "SeatedPassengerCapacity", required = true)
    protected BigInteger seatedPassengerCapacity;
    @XmlElement(name = "StandingPassengerCapacity", required = true)
    protected BigInteger standingPassengerCapacity;
    @XmlElement(required = true)
    protected BigInteger debtCollectorIdUser;

    /**
     * Gets the value of the licensePlateBus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicensePlateBus() {
        return licensePlateBus;
    }

    /**
     * Sets the value of the licensePlateBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicensePlateBus(String value) {
        this.licensePlateBus = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the seatedPassengerCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeatedPassengerCapacity() {
        return seatedPassengerCapacity;
    }

    /**
     * Sets the value of the seatedPassengerCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeatedPassengerCapacity(BigInteger value) {
        this.seatedPassengerCapacity = value;
    }

    /**
     * Gets the value of the standingPassengerCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStandingPassengerCapacity() {
        return standingPassengerCapacity;
    }

    /**
     * Sets the value of the standingPassengerCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStandingPassengerCapacity(BigInteger value) {
        this.standingPassengerCapacity = value;
    }

    /**
     * Gets the value of the debtCollectorIdUser property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDebtCollectorIdUser() {
        return debtCollectorIdUser;
    }

    /**
     * Sets the value of the debtCollectorIdUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDebtCollectorIdUser(BigInteger value) {
        this.debtCollectorIdUser = value;
    }

}
