//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.19 at 05:42:11 PM COT 
//


package com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBusByLicensePlateRequest }
     * 
     */
    public GetBusByLicensePlateRequest createGetBusByLicensePlateRequest() {
        return new GetBusByLicensePlateRequest();
    }

    /**
     * Create an instance of {@link GetBusByLicensePlateResponse }
     * 
     */
    public GetBusByLicensePlateResponse createGetBusByLicensePlateResponse() {
        return new GetBusByLicensePlateResponse();
    }

    /**
     * Create an instance of {@link Bus }
     * 
     */
    public Bus createBus() {
        return new Bus();
    }

    /**
     * Create an instance of {@link GetRouteByIdRouteRequest }
     * 
     */
    public GetRouteByIdRouteRequest createGetRouteByIdRouteRequest() {
        return new GetRouteByIdRouteRequest();
    }

    /**
     * Create an instance of {@link GetRouteByIdRouteResponse }
     * 
     */
    public GetRouteByIdRouteResponse createGetRouteByIdRouteResponse() {
        return new GetRouteByIdRouteResponse();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link AddBalanceRequest }
     * 
     */
    public AddBalanceRequest createAddBalanceRequest() {
        return new AddBalanceRequest();
    }

    /**
     * Create an instance of {@link AddBalanceResponse }
     * 
     */
    public AddBalanceResponse createAddBalanceResponse() {
        return new AddBalanceResponse();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

}
