//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.19 at 05:42:11 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://viwit.com/viwitinterface/infraestructure/driven_adapter/soap/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws;
