//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.21 at 07:38:56 PM COT 
//


package com.viwit.viwitinterface.infraestructure.driven_adapter.soap.ws;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for route complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="route"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IdRoute" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="NameRoute" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InitialBusStop" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FinalBusStop" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ApproximateDuration" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mensaje" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "route", propOrder = {
    "idRoute",
    "nameRoute",
    "initialBusStop",
    "finalBusStop",
    "approximateDuration",
    "mensaje"
})
public class Route {

    @XmlElement(name = "IdRoute", required = true)
    protected BigInteger idRoute;
    @XmlElement(name = "NameRoute", required = true)
    protected String nameRoute;
    @XmlElement(name = "InitialBusStop", required = true)
    protected String initialBusStop;
    @XmlElement(name = "FinalBusStop", required = true)
    protected String finalBusStop;
    @XmlElement(name = "ApproximateDuration", required = true)
    protected String approximateDuration;
    @XmlElement(required = true)
    protected String mensaje;

    /**
     * Gets the value of the idRoute property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdRoute() {
        return idRoute;
    }

    /**
     * Sets the value of the idRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdRoute(BigInteger value) {
        this.idRoute = value;
    }

    /**
     * Gets the value of the nameRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRoute() {
        return nameRoute;
    }

    /**
     * Sets the value of the nameRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRoute(String value) {
        this.nameRoute = value;
    }

    /**
     * Gets the value of the initialBusStop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialBusStop() {
        return initialBusStop;
    }

    /**
     * Sets the value of the initialBusStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialBusStop(String value) {
        this.initialBusStop = value;
    }

    /**
     * Gets the value of the finalBusStop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalBusStop() {
        return finalBusStop;
    }

    /**
     * Sets the value of the finalBusStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalBusStop(String value) {
        this.finalBusStop = value;
    }

    /**
     * Gets the value of the approximateDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproximateDuration() {
        return approximateDuration;
    }

    /**
     * Sets the value of the approximateDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproximateDuration(String value) {
        this.approximateDuration = value;
    }

    /**
     * Gets the value of the mensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * Sets the value of the mensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensaje(String value) {
        this.mensaje = value;
    }

}
